# default config
baseURL = "https://planttr.netlify.app"
languageCode = "en-us"
title = "PLANTTR"
theme = "parsa-hugo"
summaryLength = "10"
paginate = 9
enableEmoji = true

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# navigation

[[menu.main]]
name = "Recetas"
URL = "Recetas"
weight = 1

[[menu.main]]
name = "Finger Food"
URL = "categories/finger-food"
parent ="Recetas"
weight = 0

[[menu.main]]
name = "Snacks"
URL = "categories/snack"
parent ="Recetas"
weight = 1

[[menu.main]]
name = "Ensaladas"
URL = "categories/ensalada"
parent ="Recetas"
weight = 2

[[menu.main]]
name = "Sopas"
URL = "categories/sopa"
parent ="Recetas"
weight = 3

[[menu.main]]
name = "Platos Principales"
URL = "categories/plato-principal"
parent ="Recetas"
weight = 4

[[menu.main]]
name = "Segundos"
URL = "categories/segundos"
parent ="Recetas"
weight = 5

[[menu.main]]
name = "Guarniciones"
URL = "categories/guarnici√≥n"
parent ="Recetas"
weight = 6



[[menu.main]]
name = "Postres"
URL = "categories/postre"
parent ="Recetas"
weight = 7

[[menu.main]]
name = "guia vegana"
URL = "hello"
weight = 2

# default parameters
[params]
logo = "images/logo.png"
home = "Home"
# theme layout ( two layout is available, "1" and "2" )
layout = "1"
# Meta data
description = "A plant-based recipes database by Klaoe. We need a longer description of the site here to occupy at least 3 or 4 lines of text."
# Preloader
preloader = true
# search
search = true
# about author
author = "Klaoe"
author_image = "images/banner-img.png"
bio = "A plant-based recipes database by Klaoe."
# Contact info
mobile = "+90 666 333 22"
email = "example@ymail.com"
address = "6 rip carl Avenue CA 90733"
# Contact Form Action
contact_form_action = "#"
# Google Analitycs
google_analitycs_id = "Your ID"
# copyright
copyright = "Copyright &copy; 2020"

# Instagram feed
[params.instafeed]
enable = true
user_id = "4044026246"
access_token = "4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"

# social site
[[params.social]]
icon = "ti-facebook"
URL = "#"

[[params.social]]
icon = "ti-twitter-alt"
URL = "#"
